name: Java CI
on:
  push:
    branches: [ main, bk-reflect/main ]
  pull_request:
    branches: [ main, bk-reflect/main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bk-reflect
          path: build/libs